/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sign-ups/phone-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 문자 인증 번호 받기 */
        post: operations["createPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sign-ups/phone-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문자 인증 번호 확인
         * @description 인증 번호와 생년월일을 확인한다. 번호가 기존 계정과 겹치면 409이고, 안내 정보는 가입 진행 상태 조회로 받는다
         */
        post: operations["confirmPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sign-ups/email-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증 메일 받기
         * @description 이메일·비밀번호를 받아 인증 메일을 보낸다. 카카오가 이메일을 주지 않아 이어 온 가입이면 쿠키의 가입 진행에 붙는다
         */
        post: operations["createEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sign-ups/email-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증 링크 확인
         * @description CONTINUE_SIGN_UP이면 가입 진행 쿠키를 쓴다. SIGNED_IN이면 기존 계정에 연결하고 리프레시 쿠키와 토큰을 준다
         */
        post: operations["confirmEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입 완료
         * @description 쿠키의 가입 진행으로 ACTIVE 회원을 만들고 로그인시킨다. 리프레시 토큰은 쿠키로 주고 가입 진행 쿠키는 지운다
         */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description 리프레시 토큰으로 액세스 토큰을 다시 받는다. 리프레시 토큰도 새 것으로 바뀐다
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 리프레시 토큰을 폐기한다. 토큰이 없거나 이미 폐기됐어도 성공한다
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sign-ups/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 가입 진행 상태 */
        get: operations["getSignUp"];
        put?: never;
        post?: never;
        /**
         * 가입 취소
         * @description 가입 진행을 지운다. 회원은 생기지 않는다. 가입 진행이 없어도 성공한다
         */
        delete: operations["cancelSignUp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 동의 화면으로 이동
         * @description state를 쿠키(oauth_state)에 두고 제공자 동의 화면으로 보낸다
         */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 제공자 콜백
         * @description 로그인이면 리프레시 쿠키를 쓰고 홈으로, 새 가입이면 가입 진행 쿠키를 쓰고 /signup/phone(카카오가 이메일을 주지 않으면 /signup/email)으로, 실패면 시작 화면에 error=오류 코드(A007, B003)를 붙여 보낸다
         */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 오류 응답 */
        ErrorResponse: {
            /**
             * @description 에러 코드
             * @example V001
             */
            code?: string;
            /** @description 사용자에게 보여줄 문장 */
            message?: string;
            /**
             * Format: date-time
             * @description 발생 시각
             */
            timestamp?: string;
            /** @description 요청 경로 */
            path?: string;
            /** @description 요청 추적 ID. 서버 로그와 같은 값 */
            traceId?: string;
            /** @description 필드별 검증 오류. V001일 때만 있다 */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description 필드별 검증 오류 */
        FieldError: {
            /**
             * @description 필드
             * @example email
             */
            field?: string;
            /** @description 사유 */
            message?: string;
        };
        /** @description 문자 인증 번호 요청 */
        PhoneVerificationCreateRequest: {
            /**
             * @description 휴대폰 번호. 숫자만
             * @example 01012345678
             */
            phoneNumber: string;
        };
        /** @description 보낸 문자 인증 번호 */
        PhoneVerificationGetResponse: {
            /**
             * Format: date-time
             * @description 인증 번호 만료 시각
             */
            expiresAt?: string;
            /**
             * Format: date-time
             * @description 다시 받을 수 있는 시각
             */
            resendAvailableAt?: string;
        };
        /** @description 문자 인증 번호 확인과 생년월일 */
        PhoneConfirmationCreateRequest: {
            /**
             * @description 인증 번호 6자리
             * @example 123456
             */
            verificationCode: string;
            /**
             * Format: date
             * @description 생년월일
             * @example 2000-01-31
             */
            birthDate: string;
        };
        /** @description 가입 인증 메일 요청. 비밀번호 확인 입력은 화면에서만 검사한다 */
        EmailVerificationCreateRequest: {
            /**
             * @description 가입할 이메일
             * @example gamer@naver.com
             */
            email: string;
            /** @description 비밀번호. 8~20자, 영문과 숫자를 각각 1자 이상 */
            password: string;
        };
        /** @description 보낸 인증 메일 */
        EmailVerificationGetResponse: {
            /** @description 보낸 주소 */
            email?: string;
            /**
             * Format: date-time
             * @description 링크 만료 시각
             */
            expiresAt?: string;
            /**
             * Format: date-time
             * @description 다시 보낼 수 있는 시각
             */
            resendAvailableAt?: string;
        };
        /** @description 이메일 인증 링크 확인. 화면이 링크의 token 값을 그대로 보낸다 */
        EmailConfirmationCreateRequest: {
            /** @description 인증 링크의 token */
            token: string;
        };
        /** @description 이메일 인증 결과. SIGNED_IN이면 토큰을 함께 준다 (리프레시 토큰은 쿠키) */
        EmailConfirmationGetResponse: {
            /**
             * @description CONTINUE_SIGN_UP: 휴대폰 인증으로 이어 감. SIGNED_IN: 기존 계정에 연결·로그인
             * @enum {string}
             */
            result?: "CONTINUE_SIGN_UP" | "SIGNED_IN";
            /** @description 액세스 토큰. SIGNED_IN일 때만 */
            accessToken?: string;
            /**
             * @description 토큰 유형. SIGNED_IN일 때만
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description 액세스 토큰 남은 시간(초). SIGNED_IN일 때만
             * @example 900
             */
            expiresIn?: number;
            /** @description 리프레시 토큰. SIGNED_IN이고 앱(X-Client-Type: app)일 때만 */
            refreshToken?: string;
        };
        /** @description 가입 완료. 이메일·비밀번호·제공자 계정·생년월일·휴대폰 번호는 가입 진행에서 가져온다 */
        MemberCreateRequest: {
            /**
             * @description 닉네임. 2~12자, 한글·영문·숫자·밑줄
             * @example moa_gamer
             */
            nickname: string;
            /** @description [필수] 이용약관 동의 */
            termsAgreed?: boolean;
            /** @description [필수] 개인정보 수집·이용 동의 (이메일, 생년월일, 휴대폰 번호) */
            privacyAgreed?: boolean;
        };
        /** @description 토큰 발급 응답 */
        AuthRefreshResponse: {
            /** @description 액세스 토큰 */
            accessToken?: string;
            /**
             * @description 토큰 유형
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description 액세스 토큰 남은 시간(초)
             * @example 900
             */
            expiresIn?: number;
            /** @description 리프레시 토큰. 앱(X-Client-Type: app)에만 준다 */
            refreshToken?: string;
        };
        /** @description 토큰 재발급·로그아웃 요청. 앱만 본문을 보낸다. 웹은 쿠키로 보내므로 본문이 없다 */
        AuthRefreshRequest: {
            /** @description 리프레시 토큰 (앱) */
            refreshToken?: string;
        };
        /** @description 휴대폰 번호 중복 안내 */
        PhoneConflict: {
            /** @description 겹친 계정의 상태 (ACTIVE, SUSPENDED, WITHDRAWN, PURGED) */
            accountStatus?: string;
            /** @description 가린 기존 계정 이메일. ACTIVE·SUSPENDED일 때만 */
            maskedEmail?: string;
        };
        /** @description 가입 진행 상태. 가입하는 본인에게만 준다 */
        SignUpGetResponse: {
            /** @description 계정 이메일. 카카오가 이메일을 주지 않아 아직 정해지지 않았으면 null */
            email?: string;
            /**
             * @description 구글·카카오 가입이면 제공자, 이메일 가입이면 null
             * @enum {string}
             */
            provider?: "GOOGLE" | "KAKAO";
            /** @description 휴대폰 인증을 마쳤는지 */
            phoneVerified?: boolean;
            /** @description 인증한 휴대폰 번호가 기존 계정과 겹치면 안내 정보, 아니면 null */
            phoneConflict?: components["schemas"]["PhoneConflict"];
            /**
             * Format: date-time
             * @description 가입 진행 만료 시각
             */
            expiresAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPhoneVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerificationCreateRequest"];
            };
        };
        responses: {
            /** @description 보냄 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PhoneVerificationGetResponse"];
                };
            };
            /** @description V001 입력 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A006 가입 진행 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B015 계정 이메일이 아직 없음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B008 60초 안에 다시 받음, B009 하루 10회 넘음 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description S003 발송 실패 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmPhoneVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneConfirmationCreateRequest"];
            };
        };
        responses: {
            /** @description 확인 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description V001 입력 오류, B005 번호 틀림, B006 만료, B007 입력 횟수 넘음, B010 만 14세 미만 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A006 가입 진행 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B011 활동 중 계정과 겹침, B012 정지 계정과 겹침, B013 탈퇴 유예 계정과 겹침, B014 재가입 제한 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationCreateRequest"];
            };
        };
        responses: {
            /** @description 보냄 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmailVerificationGetResponse"];
                };
            };
            /** @description V001 입력 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A006 가입 진행 무효 (쿠키가 있을 때) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B002 비밀번호가 있는 기존 계정의 이메일 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B008 60초 안에 다시 보냄 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description S002 발송 실패 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailConfirmationCreateRequest"];
            };
        };
        responses: {
            /** @description 확인 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmailConfirmationGetResponse"];
                };
            };
            /** @description B004 만료·이미 쓴 링크 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A006 이어 온 구글·카카오 가입 진행이 만료됨 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B002 비밀번호가 있는 기존 계정의 이메일, B016 정지 계정의 이메일, B017 탈퇴 유예 계정의 이메일, B003 기존 계정에 같은 제공자의 다른 계정이 연결됨 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreateRequest"];
            };
        };
        responses: {
            /** @description 가입·로그인 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthRefreshResponse"];
                };
            };
            /** @description V001 입력 오류(닉네임 규칙, 필수 동의), B010 만 14세 미만 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A006 가입 진행 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description B015 인증 미완료, B011~B014 휴대폰 번호 겹침·재가입 제한, B002 이메일 이미 가입(이메일 가입), B003 이메일 이미 가입·제공자 계정 이미 연결(구글·카카오 가입), R003 닉네임 중복 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: {
                /** @description 앱이면 app. 리프레시 토큰을 본문으로 주고받는다 */
                "X-Client-Type"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthRefreshResponse"];
                };
            };
            /** @description A003 무효·만료, A004 재사용 감지 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description 로그아웃 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSignUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignUpGetResponse"];
                };
            };
            /** @description A006 가입 진행 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelSignUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorize: {
        parameters: {
            query?: {
                /** @description 시작한 화면. SIGN_UP이면 실패 때 가입 화면, SIGN_IN이면 로그인 화면으로 돌아간다 */
                intent?: string;
            };
            header?: never;
            path: {
                /** @description google 또는 kakao */
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 제공자로 이동 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description R001 모르는 제공자 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프론트로 이동 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
